version: '3.8'

services:
  db:  # MySQL Database Service
    image: mysql:8.0.11  # เลือกใช้ MySQL เวอร์ชัน 5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: dbreportfall  # ชื่อฐานข้อมูล
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"  # เปิดพอร์ตสำหรับเชื่อมต่อจากภายนอก
    volumes:
      - mysql_data:/var/lib/mysql  # เก็บข้อมูลถาวรใน Docker Volume

  web:  # Django Web Service
    build: ./django  # โฟลเดอร์ที่มี Dockerfile ของ Django
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/Dev_tool-Project # เมานท์โค้ดของ Django เข้าไปใน container
    ports:
      - "8000:8000"  # เปิดพอร์ตสำหรับการเข้าถึง Django
    depends_on:
      - db  # รอให้ db service เริ่มทำงานก่อน
    environment:
      - DB_HOST = db  # ชื่อ service ของ MySQL ใน docker-compose เป็น host ของฐานข้อมูล
      - DB_NAME = dbreportfall
      - DB_USER = root
      - DB_PASSWORD = ''

volumes:
  mysql_data:  # กำหนด Docker Volume สำหรับเก็บข้อมูล MySQL
