# Generated by Django 4.2.16 on 2024-10-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(max_length=40)),
                ('auth_token', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
    ]
