# Generated by Django 4.2.16 on 2024-10-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_customer_contact_contact_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='speed',
        ),
        migrations.AddField(
            model_name='sensor',
            name='accelerationX',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='accelerationY',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='accelerationZ',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='alpha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='beta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='gamma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sensor',
            name='magnitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
