# Generated by Django 4.2.16 on 2024-10-12 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_remove_sensor_location_remove_sensor_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallevent',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='report.sensor'),
        ),
    ]
